#  no longer using dropbox paperclip

# app_key: "3dhqx5aki59znr5"
# app_secret: "perzpvqi5au5nvk"
# access_token: "ck92aagskc29u5ms"
# access_token_secret: "0q7pzezq73vrh2z"
# user_id: "254696"
# access_type: "dropbox"

