# require 'spec_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to specify the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator.  If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails.  There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
# #
# # Compared to earlier versions of this generator, there is very limited use of
# # stubs and message expectations in this spec.  Stubs are only used when there
# # is no simpler way to get a handle on the object needed for the example.
# # Message expectations are only used when there is no simpler way to specify
# # that an instance is receiving a specific message.

# describe LegislationVoicesController do

#   # This should return the minimal set of attributes required to create a valid
#   # LegislationVoice. As you add validations to LegislationVoice, be sure to
#   # adjust the attributes here as well.
#   let(:valid_attributes) { { "user" => "" } }

#   # This should return the minimal set of values that should be in the session
#   # in order to pass any filters (e.g. authentication) defined in
#   # LegislationVoicesController. Be sure to keep this updated too.
#   let(:valid_session) { {} }

#   describe "GET index" do
#     it "assigns all legislation_voices as @legislation_voices" do
#       legislation_voice = LegislationVoice.create! valid_attributes
#       get :index, {}, valid_session
#       assigns(:legislation_voices).should eq([legislation_voice])
#     end
#   end

#   describe "GET show" do
#     it "assigns the requested legislation_voice as @legislation_voice" do
#       legislation_voice = LegislationVoice.create! valid_attributes
#       get :show, {:id => legislation_voice.to_param}, valid_session
#       assigns(:legislation_voice).should eq(legislation_voice)
#     end
#   end

#   describe "GET new" do
#     it "assigns a new legislation_voice as @legislation_voice" do
#       get :new, {}, valid_session
#       assigns(:legislation_voice).should be_a_new(LegislationVoice)
#     end
#   end

#   describe "GET edit" do
#     it "assigns the requested legislation_voice as @legislation_voice" do
#       legislation_voice = LegislationVoice.create! valid_attributes
#       get :edit, {:id => legislation_voice.to_param}, valid_session
#       assigns(:legislation_voice).should eq(legislation_voice)
#     end
#   end

#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new LegislationVoice" do
#         expect {
#           post :create, {:legislation_voice => valid_attributes}, valid_session
#         }.to change(LegislationVoice, :count).by(1)
#       end

#       it "assigns a newly created legislation_voice as @legislation_voice" do
#         post :create, {:legislation_voice => valid_attributes}, valid_session
#         assigns(:legislation_voice).should be_a(LegislationVoice)
#         assigns(:legislation_voice).should be_persisted
#       end

#       it "redirects to the created legislation_voice" do
#         post :create, {:legislation_voice => valid_attributes}, valid_session
#         response.should redirect_to(LegislationVoice.last)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns a newly created but unsaved legislation_voice as @legislation_voice" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         LegislationVoice.any_instance.stub(:save).and_return(false)
#         post :create, {:legislation_voice => { "user" => "invalid value" }}, valid_session
#         assigns(:legislation_voice).should be_a_new(LegislationVoice)
#       end

#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         LegislationVoice.any_instance.stub(:save).and_return(false)
#         post :create, {:legislation_voice => { "user" => "invalid value" }}, valid_session
#         response.should render_template("new")
#       end
#     end
#   end

#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested legislation_voice" do
#         legislation_voice = LegislationVoice.create! valid_attributes
#         # Assuming there are no other legislation_voices in the database, this
#         # specifies that the LegislationVoice created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         LegislationVoice.any_instance.should_receive(:update).with({ "user" => "" })
#         put :update, {:id => legislation_voice.to_param, :legislation_voice => { "user" => "" }}, valid_session
#       end

#       it "assigns the requested legislation_voice as @legislation_voice" do
#         legislation_voice = LegislationVoice.create! valid_attributes
#         put :update, {:id => legislation_voice.to_param, :legislation_voice => valid_attributes}, valid_session
#         assigns(:legislation_voice).should eq(legislation_voice)
#       end

#       it "redirects to the legislation_voice" do
#         legislation_voice = LegislationVoice.create! valid_attributes
#         put :update, {:id => legislation_voice.to_param, :legislation_voice => valid_attributes}, valid_session
#         response.should redirect_to(legislation_voice)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns the legislation_voice as @legislation_voice" do
#         legislation_voice = LegislationVoice.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         LegislationVoice.any_instance.stub(:save).and_return(false)
#         put :update, {:id => legislation_voice.to_param, :legislation_voice => { "user" => "invalid value" }}, valid_session
#         assigns(:legislation_voice).should eq(legislation_voice)
#       end

#       it "re-renders the 'edit' template" do
#         legislation_voice = LegislationVoice.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         LegislationVoice.any_instance.stub(:save).and_return(false)
#         put :update, {:id => legislation_voice.to_param, :legislation_voice => { "user" => "invalid value" }}, valid_session
#         response.should render_template("edit")
#       end
#     end
#   end

#   describe "DELETE destroy" do
#     it "destroys the requested legislation_voice" do
#       legislation_voice = LegislationVoice.create! valid_attributes
#       expect {
#         delete :destroy, {:id => legislation_voice.to_param}, valid_session
#       }.to change(LegislationVoice, :count).by(-1)
#     end

#     it "redirects to the legislation_voices list" do
#       legislation_voice = LegislationVoice.create! valid_attributes
#       delete :destroy, {:id => legislation_voice.to_param}, valid_session
#       response.should redirect_to(legislation_voices_url)
#     end
#   end

# end
